name = "alpha-edge-website1"
main = "worker/index.js"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[r2_buckets]]
binding = "UPLOADS_BUCKET"
bucket_name = "alpha-edge-uploads"